import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Footer from '@/components/layout/Footer';
import Sidebar from '@/components/layout/Sidebar';

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "VA Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col h-screen`}>
        <div className={`flex flex-row h-screen w-full`}>
          <Sidebar />
          <div className={`flex flex-col w-full`}>
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
